#
# Routing configuration for Equed.LMS
#
# Custom route for certificate display by record ID
-
  route: '/certificate/{record}'
  defaults:
    _controller: 'Equed\\EquedLms\\Controller\\CertificateController::showCardAction'
  requirements:
    record: '\\d+'
