name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: cs2pr, phpstan, phpcs, phpcbf

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHP CodeSniffer
        run: phpcs -q --report=checkstyle | cs2pr

      - name: Run PHPStan
        run: phpstan analyse --configuration=phpstan.neon
